data:
  seed: 42

checkpoint:
  path: "trained_models/model__whisper_mesonet__1721628372.9526913/ckpt.pth"

model:
  name: "whisper_frontend_mesonet"
  parameters:
    freeze_encoder: false
    input_channels: 2
    fc1_dim: 1024
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 0.00001
    weight_decay: 0.0001