data:
  seed: 42

checkpoint:
  path: ""

model:
  name: "mesonet"
  parameters:
    input_channels: 1
    fc1_dim: 1024
    # frontend_algorithm: ["lfcc"]
    frontend_algorithm: ["mfcc"]

  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
