data:
  seed: 42

checkpoint:
  path: ""

model:
  name: "specrnet"
  parameters:
    input_channels: 1
    frontend_algorithm: ["lfcc"] #1
    # frontend_algorithm: ["mfcc"]  #2
    
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
